-- PostgreSQL only. Apply to a restored staging database first, with the application stopped.
-- Requires a separately verified backup. All changes below commit or roll back together.
BEGIN;
SELECT pg_advisory_xact_lock(hashtext('newave_flow_schema'));
CREATE TABLE IF NOT EXISTS schema_migrations (
    version varchar(80) PRIMARY KEY,
    applied_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = 'V001_security_shared_reports_history') THEN
        RAISE EXCEPTION 'V001 is already applied';
    END IF;
END $$;

LOCK TABLE users, class_groups, students, attendances, daily_reports, events,
    event_student_attendances, event_attendances, tts_item IN SHARE ROW EXCLUSIVE MODE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version bigint NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS roster_captured_at timestamp;

CREATE TABLE completed_operations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint NOT NULL,
    operation_key varchar(64) NOT NULL,
    fingerprint varchar(64) NOT NULL,
    result_json text NOT NULL,
    completed_at timestamp NOT NULL,
    UNIQUE (actor_id, operation_key)
);

-- Preserve every original report, including notes and previous authors.
CREATE TABLE daily_reports_before_class_merge AS TABLE daily_reports;
WITH merged AS (
    SELECT class_group_id, report_date, min(id) AS keep_id,
           bool_or(status = 'SUBMITTED') AS submitted,
           max(submitted_at) AS submitted_at, max(updated_at) AS updated_at,
           string_agg(DISTINCT nullif(special_notes, ''), E'\n') AS notes
    FROM daily_reports GROUP BY class_group_id, report_date
), actual AS (
    SELECT class_group_id, attendance_date,
           count(*) AS total, count(*) FILTER (WHERE status = 'PRESENT') AS present,
           count(*) FILTER (WHERE status = 'ABSENT') AS absent,
           count(*) FILTER (WHERE status = 'LATE') AS late
    FROM attendances GROUP BY class_group_id, attendance_date
)
UPDATE daily_reports r SET
    status = CASE WHEN m.submitted THEN 'SUBMITTED' ELSE 'DRAFT' END,
    submitted_at = m.submitted_at, updated_at = m.updated_at, special_notes = m.notes,
    total_students = coalesce(a.total, 0), present_count = coalesce(a.present, 0),
    absent_count = coalesce(a.absent, 0), late_count = coalesce(a.late, 0)
FROM merged m LEFT JOIN actual a ON a.class_group_id = m.class_group_id AND a.attendance_date = m.report_date
WHERE r.id = m.keep_id;

DELETE FROM daily_reports r WHERE EXISTS (
    SELECT 1 FROM daily_reports keeper WHERE keeper.class_group_id = r.class_group_id
      AND keeper.report_date = r.report_date AND keeper.id < r.id
);
ALTER TABLE daily_reports ADD CONSTRAINT uk_report_class_date UNIQUE (class_group_id, report_date);
UPDATE daily_reports r SET teacher_id = (
    SELECT original.teacher_id FROM daily_reports_before_class_merge original
    WHERE original.class_group_id=r.class_group_id AND original.report_date=r.report_date
    ORDER BY original.updated_at DESC NULLS LAST, original.id DESC LIMIT 1
);

CREATE TABLE event_participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL,
    kind varchar(10) NOT NULL,
    person_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    grade varchar(255), class_group_id bigint, class_group_name varchar(255),
    captured_at timestamp NOT NULL,
    UNIQUE (event_id, kind, person_id)
);

-- This is a conversion-time baseline, not a reconstruction of unknown historical membership.
-- Retain inactive people who actually have a saved attendance record.
CREATE TEMPORARY TABLE events_to_capture ON COMMIT DROP AS
SELECT e.id FROM events e WHERE e.attendance_required = true
    OR EXISTS (SELECT 1 FROM event_student_attendances a WHERE a.event_id=e.id)
    OR EXISTS (SELECT 1 FROM event_attendances a WHERE a.event_id=e.id);
INSERT INTO event_participants (event_id,kind,person_id,name,grade,class_group_id,class_group_name,captured_at)
SELECT e.id,'STUDENT',s.id,s.name,s.grade,coalesce(s.class_group_id,0),coalesce(c.name,'미배정'),CURRENT_TIMESTAMP
FROM events e CROSS JOIN students s LEFT JOIN class_groups c ON c.id=s.class_group_id
WHERE e.id IN (SELECT id FROM events_to_capture) AND (
    (s.is_active = true AND s.class_group_id IS NOT NULL)
    OR EXISTS (SELECT 1 FROM event_student_attendances a WHERE a.event_id=e.id AND a.student_id=s.id)
);

INSERT INTO event_participants (event_id,kind,person_id,name,grade,captured_at)
SELECT e.id,'TEACHER',u.id,u.name,coalesce(nullif(u.grade,''),
    (SELECT c.age_group FROM teacher_classes tc JOIN class_groups c ON c.id=tc.class_group_id
      WHERE tc.teacher_id=u.id ORDER BY tc.is_primary DESC,tc.id LIMIT 1)),CURRENT_TIMESTAMP
FROM events e CROSS JOIN users u
WHERE e.id IN (SELECT id FROM events_to_capture) AND u.role <> 'ADMIN' AND (
    u.is_active = true OR EXISTS (SELECT 1 FROM event_attendances a WHERE a.event_id=e.id AND a.teacher_id=u.id)
);
UPDATE events SET roster_captured_at=CURRENT_TIMESTAMP WHERE id IN (SELECT id FROM events_to_capture);

CREATE TABLE tts_question_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id bigint NOT NULL, effective_from date NOT NULL,
    title varchar(255) NOT NULL, type varchar(255) NOT NULL,
    emoji varchar(255), display_order integer, active boolean NOT NULL,
    points integer, link_type varchar(255),
    UNIQUE (question_id,effective_from)
);
INSERT INTO tts_question_revisions (question_id,effective_from,title,type,emoji,display_order,active,points,link_type)
SELECT id,DATE '1900-01-01',title,q_type,emoji,display_order,is_active,points,link_type FROM tts_item;

INSERT INTO schema_migrations(version) VALUES ('V001_security_shared_reports_history');
COMMIT;
